services:
  husto_language_studio:
    build:
      context: .
    image: husto_language_studio
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
      - my_media:/files/media
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - db


  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:
  my_media:
