# Generated by Django 5.1 on 2024-09-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("english_school", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="type",
            new_name="course_type",
        ),
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.TimeField(default="00:00:00"),
            preserve_default=False,
        ),
    ]
